// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: int-enum (SafeBrowsingResponseAction) glue plus the
// fork's constructor defaults (report = true, action = SHOW_INTERSTITIAL).

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'safe_browsing_response.zorphy.dart';
part 'safe_browsing_response.g.dart';

///Class that represents the response used by the [PlatformWebViewCreationParams.onSafeBrowsingHit] event.
///It is used to indicate an action to take when hitting a malicious URL.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $SafeBrowsingResponse {
  ///If reporting is enabled, all reports will be sent according to the privacy policy referenced by [PlatformInAppWebViewController.getSafeBrowsingPrivacyPolicyUrl].
  @JsonKey(defaultValue: true)
  bool? get report;

  ///Indicate the [SafeBrowsingResponseAction] to take when hitting a malicious URL.
  @JsonKey(
    defaultValue: SafeBrowsingResponseAction.SHOW_INTERSTITIAL,
    fromJson: _actionFromJson,
    toJson: _actionToJson,
  )
  SafeBrowsingResponseAction? get action;
}

SafeBrowsingResponseAction? _actionFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < SafeBrowsingResponseAction.values.length
      ? SafeBrowsingResponseAction.values[index]
      : null;
}

Object? _actionToJson(SafeBrowsingResponseAction? action) => action?.index;
