// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: WebUri field glue plus the fork's constructor default
// (retain = false).
//
// Import for the external (non-entity) type WebUri was hand-corrected
// (zuraffa#349: zfa emits a `$` prefix + bogus import for types outside
// lib/src/domain/entities).

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../../../web_uri.dart';

part 'geolocation_permission_show_prompt_response.zorphy.dart';
part 'geolocation_permission_show_prompt_response.g.dart';

///Class used by the host application to set the Geolocation permission state for an origin during the [PlatformWebViewCreationParams.onGeolocationPermissionsShowPrompt] event.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $GeolocationPermissionShowPromptResponse {
  ///The origin for which permissions are set.
  @JsonKey(fromJson: _originFromJson, toJson: _originToJson)
  WebUri? get origin;

  ///Whether or not the origin should be allowed to use the Geolocation API.
  bool? get allow;

  ///Whether the permission should be retained beyond the lifetime of a page currently being displayed by a WebView
  ///The default value is `false`.
  @JsonKey(defaultValue: false)
  bool? get retain;
}

WebUri? _originFromJson(Object? value) =>
    value == null ? null : WebUri(value as String);

Object? _originToJson(WebUri? value) => value?.toString();
