// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: WebUri / string-wire enum (ReferrerPolicy) / int enum
// (FetchRequestAction) / Map / polymorphic-credential wire glue plus the
// fork's constructor default (action = FetchRequestAction.PROCEED).
//
// Imports for the external (non-entity) types WebUri, ReferrerPolicy and the
// hand-written FetchRequestCredential hierarchy were hand-corrected
// (zuraffa#349: zfa emits a `$` prefix + bogus import for types outside
// lib/src/domain/entities).

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../../../types/fetch_request_credential.dart';
import '../../../types/fetch_request_credential_default.dart';
import '../../../types/fetch_request_federated_credential.dart';
import '../../../types/fetch_request_password_credential.dart';
import '../../../types/referrer_policy.dart';
import '../../../web_uri.dart';
import '../enums/index.dart';

part 'fetch_request.zorphy.dart';
part 'fetch_request.g.dart';

///Class that represents a HTTP request created with JavaScript using the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $FetchRequest {
  ///The URL of the request.
  @JsonKey(fromJson: _urlFromJson, toJson: _urlToJson)
  WebUri? get url;

  ///The HTTP request method used of the request.
  String? get method;

  ///The HTTP request headers.
  @JsonKey(fromJson: _headersFromJson, toJson: _headersToJson)
  Map<String, dynamic>? get headers;

  ///Body of the request.
  dynamic get body;

  ///The mode used by the request.
  String? get mode;

  ///The request credentials used by the request.
  @JsonKey(fromJson: _credentialsFromJson, toJson: _credentialsToJson)
  FetchRequestCredential? get credentials;

  ///The cache mode used by the request.
  String? get cache;

  ///The redirect mode used by the request.
  String? get redirect;

  ///A String specifying no-referrer, client, or a URL.
  String? get referrer;

  ///The value of the referer HTTP header.
  @JsonKey(fromJson: _referrerPolicyFromJson, toJson: _referrerPolicyToJson)
  ReferrerPolicy? get referrerPolicy;

  ///Contains the subresource integrity value of the request.
  String? get integrity;

  ///The keepalive option used to allow the request to outlive the page.
  bool? get keepalive;

  ///Indicates the [FetchRequestAction] that can be used to control the request.
  @JsonKey(
    defaultValue: FetchRequestAction.PROCEED,
    fromJson: _actionFromJson,
    toJson: _actionToJson,
  )
  FetchRequestAction? get action;
}

WebUri? _urlFromJson(Object? value) =>
    value == null ? null : WebUri(value as String);

Object? _urlToJson(WebUri? value) => value?.toString();

Map<String, dynamic>? _headersFromJson(Object? value) =>
    value == null ? null : (value as Map).cast<String, dynamic>();

Object? _headersToJson(Map<String, dynamic>? headers) => headers;

FetchRequestCredential? _credentialsFromJson(Object? value) {
  if (value is! Map) return null;
  final map = value.cast<String, dynamic>();
  final type = map['type'];
  switch (type) {
    case 'default':
      return FetchRequestCredentialDefault.fromMap(map);
    case 'federated':
      return FetchRequestFederatedCredential.fromMap(map);
    case 'password':
      return FetchRequestPasswordCredential.fromMap(map);
  }
  return null;
}

Object? _credentialsToJson(FetchRequestCredential? credentials) =>
    credentials?.toMap();

ReferrerPolicy? _referrerPolicyFromJson(Object? value) {
  if (value is! String) return null;
  return ReferrerPolicy.fromNativeValue(value);
}

Object? _referrerPolicyToJson(ReferrerPolicy? referrerPolicy) =>
    referrerPolicy?.toNativeValue();

FetchRequestAction? _actionFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < FetchRequestAction.values.length
      ? FetchRequestAction.values[index]
      : null;
}

Object? _actionToJson(FetchRequestAction? action) => action?.index;
