// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: WebUri + Map<String,String> wire glue.
//
// Imports for the external (non-entity) type WebUri were hand-corrected
// (zuraffa#349: zfa emits a `$` prefix + bogus import for types outside
// lib/src/domain/entities).

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../../../web_uri.dart';

part 'web_resource_request.zorphy.dart';
part 'web_resource_request.g.dart';

///Class representing a resource request of the `WebView`.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $WebResourceRequest {
  ///The URL for which the resource request was made.
  @JsonKey(fromJson: _urlFromJson, toJson: _urlToJson)
  WebUri? get url;

  ///The headers associated with the request.
  ///
  ///**NOTE**: available on Android 21+. For Android < 21 it will be always `null`.
  @JsonKey(fromJson: _headersFromJson, toJson: _headersToJson)
  Map<String, String>? get headers;

  ///The method associated with the request, for example `GET`.
  ///
  ///**NOTE**: available on Android 21+. For Android < 21 it will be always "GET".
  String? get method;

  ///Gets whether a gesture (such as a click) was associated with the request.
  ///For security reasons in certain situations this method may return `false` even though
  ///the sequence of events which caused the request to be created was initiated by a user
  ///gesture.
  ///
  ///**NOTE**: available on Android 21+. For Android < 21 it will be always `false`.
  bool? get hasGesture;

  ///Whether the request was made in order to fetch the main frame's document.
  ///
  ///**NOTE**: available on Android 21+. For Android < 21 it will be always `true`.
  bool? get isForMainFrame;

  ///Whether the request was a result of a server-side redirect.
  ///
  ///**NOTE**: available on Android 21+. For Android < 21 it will be always `false`.
  bool? get isRedirect;
}

WebUri? _urlFromJson(Object? value) =>
    value == null ? null : WebUri(value as String);

Object? _urlToJson(WebUri? value) => value?.toString();

Map<String, String>? _headersFromJson(Object? value) =>
    value == null ? null : (value as Map).cast<String, String>();

Object? _headersToJson(Map<String, String>? headers) => headers;
