// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: int-wire enum glue (ConsoleMessageLevel) plus the
// fork's constructor defaults (message = "", messageLevel = LOG).

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'console_message.zorphy.dart';
part 'console_message.g.dart';

///Class representing a JavaScript console message from WebCore.
///This could be a issued by a call to one of the console logging functions (e.g. console.log('...')) or a JavaScript error on the page.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $ConsoleMessage {
  ///Console message
  @JsonKey(defaultValue: '')
  String? get message;

  ///Console message level
  @JsonKey(
    defaultValue: ConsoleMessageLevel.LOG,
    fromJson: _messageLevelFromJson,
    toJson: _messageLevelToJson,
  )
  ConsoleMessageLevel? get messageLevel;
}

ConsoleMessageLevel? _messageLevelFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < ConsoleMessageLevel.values.length
      ? ConsoleMessageLevel.values[index]
      : null;
}

Object? _messageLevelToJson(ConsoleMessageLevel? messageLevel) =>
    messageLevel?.index;
