// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: constructor defaults + int action wire format.

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'js_confirm_response.zorphy.dart';
part 'js_confirm_response.g.dart';

///Class that represents the response used by the [PlatformWebViewCreationParams.onJsConfirm] event to control a JavaScript confirm dialog.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $JsConfirmResponse {
  ///Message to be displayed in the window.
  @JsonKey(defaultValue: '')
  String get message;

  ///Title of the confirm button.
  @JsonKey(defaultValue: '')
  String get confirmButtonTitle;

  ///Title of the cancel button.
  @JsonKey(defaultValue: '')
  String get cancelButtonTitle;

  ///Whether the client will handle the confirm dialog.
  @JsonKey(defaultValue: false)
  bool get handledByClient;

  ///Action used to confirm that the user hit confirm or cancel button.
  @JsonKey(
    defaultValue: JsConfirmResponseAction.CANCEL,
    fromJson: _actionFromJson,
    toJson: _actionToJson,
  )
  JsConfirmResponseAction? get action;
}

JsConfirmResponseAction? _actionFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < JsConfirmResponseAction.values.length
      ? JsConfirmResponseAction.values[index]
      : null;
}

Object? _actionToJson(JsConfirmResponseAction? action) => action?.index;
