// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: AjaxRequestEventType is a string-wire enum
// ("loadstart", "load", ...) so it needs explicit fromJson/toJson glue.

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'ajax_request_event.zorphy.dart';
part 'ajax_request_event.g.dart';

///Class used by [AjaxRequest] class. It represents events measuring progress of an [AjaxRequest].
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $AjaxRequestEvent {
  ///Event type.
  @JsonKey(fromJson: _typeFromJson, toJson: _typeToJson)
  AjaxRequestEventType? get type;

  ///Is a Boolean flag indicating if the total work to be done, and the amount of work already done, by the underlying process is calculable.
  ///In other words, it tells if the progress is measurable or not.
  bool? get lengthComputable;

  ///Is an integer representing the amount of work already performed by the underlying process.
  ///The ratio of work done can be calculated with the property and [AjaxRequestEvent.total].
  ///When downloading a resource using HTTP, this only represent the part of the content itself, not headers and other overhead.
  int? get loaded;

  ///Is an integer representing the total amount of work that the underlying process is in the progress of performing.
  ///When downloading a resource using HTTP, this only represent the content itself, not headers and other overhead.
  int? get total;
}

AjaxRequestEventType? _typeFromJson(Object? value) {
  if (value is! String) return null;
  switch (value) {
    case 'loadstart':
      return AjaxRequestEventType.LOADSTART;
    case 'load':
      return AjaxRequestEventType.LOAD;
    case 'loadend':
      return AjaxRequestEventType.LOADEND;
    case 'progress':
      return AjaxRequestEventType.PROGRESS;
    case 'error':
      return AjaxRequestEventType.ERROR;
    case 'abort':
      return AjaxRequestEventType.ABORT;
    case 'timeout':
      return AjaxRequestEventType.TIMEOUT;
  }
  return null;
}

Object? _typeToJson(AjaxRequestEventType? type) {
  switch (type) {
    case AjaxRequestEventType.LOADSTART:
      return 'loadstart';
    case AjaxRequestEventType.LOAD:
      return 'load';
    case AjaxRequestEventType.LOADEND:
      return 'loadend';
    case AjaxRequestEventType.PROGRESS:
      return 'progress';
    case AjaxRequestEventType.ERROR:
      return 'error';
    case AjaxRequestEventType.ABORT:
      return 'abort';
    case AjaxRequestEventType.TIMEOUT:
      return 'timeout';
    case null:
      return null;
  }
}
