// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: constructor defaults + int action wire format.

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'js_alert_response.zorphy.dart';
part 'js_alert_response.g.dart';

///Class that represents the response used by the [PlatformWebViewCreationParams.onJsAlert] event to control a JavaScript alert dialog.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $JsAlertResponse {
  ///Message to be displayed in the window.
  @JsonKey(defaultValue: '')
  String get message;

  ///Title of the confirm button.
  @JsonKey(defaultValue: '')
  String get confirmButtonTitle;

  ///Whether the client will handle the alert dialog.
  @JsonKey(defaultValue: false)
  bool get handledByClient;

  ///Action used to confirm that the user hit confirm button.
  @JsonKey(
    defaultValue: JsAlertResponseAction.CONFIRM,
    fromJson: _actionFromJson,
    toJson: _actionToJson,
  )
  JsAlertResponseAction? get action;
}

JsAlertResponseAction? _actionFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < JsAlertResponseAction.values.length
      ? JsAlertResponseAction.values[index]
      : null;
}

Object? _actionToJson(JsAlertResponseAction? action) => action?.index;
