// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: WebUri field glued to the fork's existing class.

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../../../web_uri.dart';

part 'js_prompt_request.zorphy.dart';
part 'js_prompt_request.g.dart';

///Class that represents the request of the [PlatformWebViewCreationParams.onJsPrompt] event.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $JsPromptRequest {
  ///The url of the page requesting the dialog.
  @JsonKey(fromJson: _urlFromJson, toJson: _urlToJson)
  WebUri? get url;

  ///Message to be displayed in the window.
  String? get message;

  ///The default value displayed in the prompt dialog.
  String? get defaultValue;

  ///Indicates whether the request was made for the main frame.
  bool? get isMainFrame;
}

WebUri? _urlFromJson(Object? value) =>
    value == null ? null : WebUri(value as String);

Object? _urlToJson(WebUri? value) => value?.toString();
