// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: constructor defaults + int action wire format.

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'js_prompt_response.zorphy.dart';
part 'js_prompt_response.g.dart';

///Class that represents the response used by the [PlatformWebViewCreationParams.onJsPrompt] event to control a JavaScript prompt dialog.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $JsPromptResponse {
  ///Message to be displayed in the window.
  @JsonKey(defaultValue: '')
  String get message;

  ///The default value displayed in the prompt dialog.
  @JsonKey(defaultValue: '')
  String get defaultValue;

  ///Title of the confirm button.
  @JsonKey(defaultValue: '')
  String get confirmButtonTitle;

  ///Title of the cancel button.
  @JsonKey(defaultValue: '')
  String get cancelButtonTitle;

  ///Whether the client will handle the prompt dialog.
  @JsonKey(defaultValue: false)
  bool get handledByClient;

  ///Value of the prompt dialog.
  String? get value;

  ///Action used to confirm that the user hit confirm or cancel button.
  @JsonKey(
    defaultValue: JsPromptResponseAction.CANCEL,
    fromJson: _actionFromJson,
    toJson: _actionToJson,
  )
  JsPromptResponseAction? get action;
}

JsPromptResponseAction? _actionFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < JsPromptResponseAction.values.length
      ? JsPromptResponseAction.values[index]
      : null;
}

Object? _actionToJson(JsPromptResponseAction? action) => action?.index;
