// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: string-wire enum glue (WebResourceErrorType; native
// value == enum name).

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'web_resource_error.zorphy.dart';
part 'web_resource_error.g.dart';

///Encapsulates information about errors occurred during loading of web resources.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $WebResourceError {
  ///The type of the error.
  @JsonKey(fromJson: _typeFromJson, toJson: _typeToJson)
  WebResourceErrorType? get type;

  ///The string describing the error.
  String? get description;
}

WebResourceErrorType? _typeFromJson(Object? value) {
  if (value is! String) return null;
  for (final type in WebResourceErrorType.values) {
    if (type.name == value) return type;
  }
  return null;
}

Object? _typeToJson(WebResourceErrorType? type) => type?.name;
