// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: WebUri / int-enum / Map / nested-object wire glue plus
// the fork's constructor default (action = AjaxRequestAction.PROCEED).
//
// Imports for the external (non-entity) types WebUri and AjaxRequestHeaders
// were hand-corrected (zuraffa#349: zfa emits a `$` prefix + bogus import for
// types outside lib/src/domain/entities).

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../ajax_request_event/ajax_request_event.dart';
import '../../../types/ajax_request_headers.dart';
import '../../../web_uri.dart';
import '../enums/index.dart';

part 'ajax_request.zorphy.dart';
part 'ajax_request.g.dart';

///Class that represents a JavaScript [XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) object.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $AjaxRequest {
  ///Data passed as a parameter to the `XMLHttpRequest.send()` method.
  dynamic get data;

  ///The HTTP request method of the `XMLHttpRequest` request.
  String? get method;

  ///The URL of the `XMLHttpRequest` request.
  @JsonKey(fromJson: _urlFromJson, toJson: _urlToJson)
  WebUri? get url;

  ///An optional Boolean parameter, defaulting to true, indicating whether or not the request is performed asynchronously.
  bool? get isAsync;

  ///The optional user name to use for authentication purposes; by default, this is the null value.
  String? get user;

  ///The optional password to use for authentication purposes; by default, this is the null value.
  String? get password;

  ///The XMLHttpRequest.withCredentials property is a Boolean that indicates whether or not cross-site Access-Control requests
  ///should be made using credentials such as cookies, authorization headers or TLS client certificates.
  ///Setting withCredentials has no effect on same-site requests.
  ///In addition, this flag is also used to indicate when cookies are to be ignored in the response. The default is false.
  bool? get withCredentials;

  ///The HTTP request headers.
  @JsonKey(fromJson: _headersFromJson, toJson: _headersToJson)
  AjaxRequestHeaders? get headers;

  ///The state of the `XMLHttpRequest` request.
  @JsonKey(fromJson: _readyStateFromJson, toJson: _readyStateToJson)
  AjaxRequestReadyState? get readyState;

  ///The numerical HTTP [status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status) of the `XMLHttpRequest`'s response.
  int? get status;

  ///The serialized URL of the response or the empty string if the URL is null.
  ///If the URL is returned, any URL fragment present in the URL will be stripped away.
  ///The value of responseURL will be the final URL obtained after any redirects.
  @JsonKey(fromJson: _responseURLFromJson, toJson: _responseURLToJson)
  WebUri? get responseURL;

  ///It is an enumerated string value specifying the type of data contained in the response.
  ///It also lets the author change the [response type](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType).
  ///If an empty string is set as the value of responseType, the default value of text is used.
  String? get responseType;

  ///The response's body content. The content-type depends on the [AjaxRequest.responseType].
  dynamic get response;

  ///The text received from a server following a request being sent.
  String? get responseText;

  ///The HTML or XML string retrieved by the request or null if the request was unsuccessful, has not yet been sent, or if the data can't be parsed as XML or HTML.
  String? get responseXML;

  ///A String containing the response's status message as returned by the HTTP server.
  ///Unlike [AjaxRequest.status] which indicates a numerical status code, this property contains the text of the response status, such as "OK" or "Not Found".
  ///If the request's readyState is in [AjaxRequestReadyState.UNSENT] or [AjaxRequestReadyState.OPENED] state, the value of statusText will be an empty string.
  ///If the server response doesn't explicitly specify a status text, statusText will assume the default value "OK".
  String? get statusText;

  ///All the response headers or returns null if no response has been received. If a network error happened, an empty string is returned.
  @JsonKey(fromJson: _responseHeadersFromJson, toJson: _responseHeadersToJson)
  Map<String, dynamic>? get responseHeaders;

  ///Event type of the `XMLHttpRequest` request.
  @JsonKey(fromJson: _eventFromJson, toJson: _eventToJson)
  AjaxRequestEvent? get event;

  ///Indicates the [AjaxRequestAction] that can be used to control the `XMLHttpRequest` request.
  @JsonKey(
    defaultValue: AjaxRequestAction.PROCEED,
    fromJson: _actionFromJson,
    toJson: _actionToJson,
  )
  AjaxRequestAction? get action;
}

WebUri? _urlFromJson(Object? value) =>
    value == null ? null : WebUri(value as String);

Object? _urlToJson(WebUri? value) => value?.toString();

WebUri? _responseURLFromJson(Object? value) =>
    value == null ? null : WebUri(value as String);

Object? _responseURLToJson(WebUri? value) => value?.toString();

AjaxRequestHeaders? _headersFromJson(Object? value) => value == null
    ? null
    : AjaxRequestHeaders.fromMap(value as Map<String, dynamic>);

Object? _headersToJson(AjaxRequestHeaders? headers) => headers?.toMap();

AjaxRequestReadyState? _readyStateFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < AjaxRequestReadyState.values.length
      ? AjaxRequestReadyState.values[index]
      : null;
}

Object? _readyStateToJson(AjaxRequestReadyState? readyState) =>
    readyState?.index;

Map<String, dynamic>? _responseHeadersFromJson(Object? value) =>
    value == null ? null : (value as Map).cast<String, dynamic>();

Object? _responseHeadersToJson(Map<String, dynamic>? headers) => headers;

AjaxRequestEvent? _eventFromJson(Object? value) => value == null
    ? null
    : AjaxRequestEvent.fromJson(value as Map<String, dynamic>);

Object? _eventToJson(AjaxRequestEvent? event) => event?.toJson();

AjaxRequestAction? _actionFromJson(Object? value) {
  if (value is! int) return null;
  final index = value;
  return index >= 0 && index < AjaxRequestAction.values.length
      ? AjaxRequestAction.values[index]
      : null;
}

Object? _actionToJson(AjaxRequestAction? action) => action?.index;
