// Auto-generated by Zorphy (via zfa entity create) — post-processed for
// zikzak_inappwebview: Uint8List (binary body) + Map<String,String> wire glue
// plus the fork's constructor defaults (contentType = "", contentEncoding =
// "utf-8"). `data` passes through raw on the method channel (arrives as
// Uint8List) and as a List<int> on JSON paths (e.g. dart:convert jsonEncode
// of a WebResourceResponse map).

import 'dart:typed_data';

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'web_resource_response.zorphy.dart';
part 'web_resource_response.g.dart';

///Class representing a resource response of the `WebView`.
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $WebResourceResponse {
  ///The resource response's MIME type, for example `text/html`.
  @JsonKey(defaultValue: '')
  String? get contentType;

  ///The resource response's encoding. The default value is `utf-8`.
  @JsonKey(defaultValue: 'utf-8')
  String? get contentEncoding;

  ///The data provided by the resource response.
  @JsonKey(fromJson: _dataFromJson, toJson: _dataToJson)
  Uint8List? get data;

  ///The headers for the resource response. If [headers] isn't `null`, then you need to set also [statusCode] and [reasonPhrase].
  ///
  ///**NOTE**: available on Android 21+. For Android < 21 it won't be used.
  @JsonKey(fromJson: _headersFromJson, toJson: _headersToJson)
  Map<String, String>? get headers;

  ///The status code needs to be in the ranges [100, 299], [400, 599]. Causing a redirect by specifying a 3xx code is not supported.
  ///If statusCode is set, then you need to set also [headers] and [reasonPhrase]. This value cannot be `null`.
  ///
  ///**NOTE**: available on Android 21+. For Android < 21 it won't be used.
  int? get statusCode;

  ///The phrase describing the status code, for example `"OK"`. Must be non-empty.
  ///If reasonPhrase is set, then you need to set also [headers] and [reasonPhrase]. This value cannot be `null`.
  ///
  ///**NOTE**: available on Android 21+. For Android < 21 it won't be used.
  String? get reasonPhrase;
}

Uint8List? _dataFromJson(Object? value) {
  if (value == null) return null;
  if (value is Uint8List) return value;
  if (value is List) {
    try {
      return Uint8List.fromList(value.cast<int>());
    } catch (_) {
      return null;
    }
  }
  return null;
}

Object? _dataToJson(Uint8List? data) => data;

Map<String, String>? _headersFromJson(Object? value) =>
    value == null ? null : (value as Map).cast<String, String>();

Object? _headersToJson(Map<String, String>? headers) => headers;
