///Pure-Dart rules for ranking and filtering DOM selector candidates.
///
///The tap listener script (`tap_listener_js.dart`) mirrors these rules in
///JavaScript; keeping them in Dart makes them unit-testable.
library;

///Max number of positional `nth-of-type` levels in a generated path.
const int kMaxPositionalPathLevels = 3;

///Max length of a normalized text content capture.
const int kMaxTextContentLength = 100;

///Rules used to build the ranked selector-candidate list for a tapped
///element. Candidates are ordered most-stable first:
///
/// 1. `#id` when the id exists and doesn't look auto-generated
/// 2. `data-testid` / `data-test` / other `data-*` attribute selectors
/// 3. `tag.cls1.cls2` with hashed/utility-looking classes filtered out
/// 4. positional `nth-of-type` path (a few levels up)
class SelectorCandidateRules {
  SelectorCandidateRules._();

  static final RegExp _longDigitRun = RegExp(r'\d{4,}');
  static final RegExp _uuidLike = RegExp(
    r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
    caseSensitive: false,
  );
  static final RegExp _longHexRun = RegExp(r'\b[0-9a-f]{8,}\b');

  ///Whether [id] looks framework-generated (long digit runs, uuid-ish, or
  ///long hex runs) and is therefore unstable across sessions.
  static bool looksAutoGeneratedId(String id) {
    final trimmed = id.trim();
    if (trimmed.isEmpty) return true;
    if (_uuidLike.hasMatch(trimmed)) return true;
    if (_longDigitRun.hasMatch(trimmed)) return true;
    if (_longHexRun.hasMatch(trimmed)) return true;
    return false;
  }

  static final RegExp _cssModuleHash = RegExp(r'^css-[a-z0-9]{4,}$');
  static final RegExp _hashedSuffix = RegExp(r'[_-]([a-zA-Z0-9]{5,})$');
  static final RegExp _pureHash = RegExp(r'^[a-z0-9]{6,}$');
  static final RegExp _hasDigit = RegExp(r'\d');

  ///Known utility-framework class prefixes (Tailwind-style).
  static const List<String> utilityPrefixes = <String>[
    'css-', // emotion
    'sc-', // styled-components
    'jss',
    'Mui', // material-ui generated
  ];

  ///Whether [cls] looks like a hashed or utility-framework class that is
  ///unstable or non-semantic, and should be filtered out of `tag.cls`
  ///candidates.
  static bool isUtilityClass(String cls) {
    final c = cls.trim();
    if (c.isEmpty) return true;
    // emotion: css-1abc2de
    if (_cssModuleHash.hasMatch(c)) return true;
    // styled-components / css-modules: sc-hash, foo_3Xy9zAb — a long
    // suffix containing digits (plain words like `menu-orders` are kept).
    final suffix = _hashedSuffix.firstMatch(c);
    if (suffix != null && _hasDigit.hasMatch(suffix.group(1)!)) return true;
    // pure hashes: 3Xy9z, e4f5a6, _3Xy9z handled by suffix rule
    if (_pureHash.hasMatch(c) && _hasDigit.hasMatch(c)) return true;
    for (final prefix in utilityPrefixes) {
      if (c.startsWith(prefix)) return true;
    }
    return false;
  }

  ///CSS-escapes a value used inside a quoted attribute selector.
  static String escapeAttributeValue(String value) {
    return value.replaceAll('\\', '\\\\').replaceAll('"', '\\"');
  }

  ///CSS-escapes an identifier (id/class) for use in a selector.
  static String escapeIdentifier(String value) {
    return value.replaceAll('\\', '\\\\').replaceAll('.', '\\.').replaceAll(
          '#',
          '\\#',
        );
  }

  ///Builds the ranked candidate list.
  ///
  ///[tagName] lowercase tag (e.g. `a`, `button`); [id] element id or null;
  ///[dataAttributes] `data-*` name → value map; [classes] class list;
  ///[positionalPath] pre-computed `nth-of-type` segments, deepest last
  ///(e.g. `['div:nth-of-type(2)', 'ul:nth-of-type(1)', 'li:nth-of-type(3)']`).
  static List<String> rankCandidates({
    required String tagName,
    String? id,
    Map<String, String>? dataAttributes,
    List<String>? classes,
    List<String>? positionalPath,
  }) {
    final candidates = <String>[];
    final tag = tagName.toLowerCase();

    // 1. #id when stable-looking.
    if (id != null && !looksAutoGeneratedId(id)) {
      candidates.add('#${escapeIdentifier(id)}');
    }

    // 2. data-testid / data-test first, then other data-* attributes.
    final data = dataAttributes ?? const <String, String>{};
    final orderedKeys = <String>[
      if (data.containsKey('data-testid')) 'data-testid',
      if (data.containsKey('data-test')) 'data-test',
      ...data.keys.where(
        (k) => k != 'data-testid' && k != 'data-test',
      ),
    ];
    for (final key in orderedKeys) {
      final value = data[key];
      if (value == null || value.isEmpty) continue;
      candidates.add('[$key="${escapeAttributeValue(value)}"]');
    }

    // 3. tag.cls1.cls2 with hashed/utility classes removed.
    final semanticClasses = (classes ?? const <String>[])
        .where((c) => !isUtilityClass(c))
        .toList();
    if (semanticClasses.isNotEmpty) {
      candidates.add(
        '$tag.${semanticClasses.map(escapeIdentifier).join('.')}',
      );
    }

    // 4. Positional nth-of-type path (limited depth).
    final path = positionalPath ?? const <String>[];
    if (path.isNotEmpty) {
      final limited = path.length > kMaxPositionalPathLevels
          ? path.sublist(path.length - kMaxPositionalPathLevels)
          : path;
      candidates.add(limited.join(' > '));
    }

    return candidates;
  }

  ///Normalizes visible text: trims, collapses whitespace, caps at
  ///[kMaxTextContentLength] characters.
  static String normalizeText(String text) {
    final normalized = text.trim().replaceAll(RegExp(r'\s+'), ' ');
    if (normalized.length <= kMaxTextContentLength) return normalized;
    return normalized.substring(0, kMaxTextContentLength);
  }
}
