///Name of the JavaScript handler the recipe tap listener reports through.
const String kRecipeTapHandlerName = '__zikzakRecipeTap__';

///Builds the JavaScript tap listener injected into every page (at document
///start, in all frames) while a `RecipeRecorder` is active.
///
///The script installs a capture-phase `click` listener that resolves the
///tapped element's actionable ancestor (`a`, `button`, `[role=button]`,
///`input`, else the target itself), builds a ranked selector-candidate list
///(mirroring the Dart-side `SelectorCandidateRules`), and reports
///`{ selectorCandidates, textContent, tagName, pageUrl }` through the
///`__zikzakRecipeTap__` JavaScript handler. Synthetic events
///(`event.isTrusted === false`, e.g. `.click()` dispatches from the
///dialogue dismisser or the replayer) are ignored — only real user taps
///are recorded. Events fired before the Dart side has registered its
///handler are buffered in-page and flushed when the recorder calls
///`window.__zikzakRecipeTap__.ready()`.
String buildRecipeTapListenerJs() => recipeTapListenerJsTemplate;

///The raw tap listener source.
const String recipeTapListenerJsTemplate = r'''
(function () {
  if (window.__zikzakRecipeTapInstalled__) return;
  window.__zikzakRecipeTapInstalled__ = true;

  var HANDLER_NAME = '__zikzakRecipeTap__';
  var MAX_QUEUE_SIZE = 200;
  var MAX_TEXT_LENGTH = 100;
  var MAX_PATH_LEVELS = 3;

  var queue = [];
  var dartReady = false;

  function bridge() {
    try {
      var b = window.zikzak_inappwebview;
      if (b && typeof b.callHandler === 'function') return b;
    } catch (e) {}
    return null;
  }

  function send(payload) {
    var b = bridge();
    if (!b) return false;
    try {
      b.callHandler(HANDLER_NAME, payload);
      return true;
    } catch (e) {
      return false;
    }
  }

  function emit(payload) {
    if (dartReady) {
      if (send(payload)) return;
    } else {
      // Optimistically send: the native handler may already be registered.
      // The event is also queued and re-sent on ready().
      send(payload);
    }
    if (queue.length < MAX_QUEUE_SIZE) queue.push(payload);
  }

  window.__zikzakRecipeTap__ = {
    ready: function () {
      dartReady = true;
      var q = queue.slice();
      queue.length = 0;
      var flushed = 0;
      for (var i = 0; i < q.length; i++) {
        if (send(q[i])) flushed++;
      }
      return flushed;
    }
  };

  // ---------------- selector candidate rules ----------------
  // Mirror of the Dart-side SelectorCandidateRules.

  function looksAutoGeneratedId(id) {
    if (!id) return true;
    if (/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i.test(id))
      return true;
    if (/\d{4,}/.test(id)) return true;
    if (/\b[0-9a-f]{8,}\b/.test(id)) return true;
    return false;
  }

  function isUtilityClass(cls) {
    if (!cls) return true;
    if (/^css-[a-z0-9]{4,}$/.test(cls)) return true;
    var suffix = cls.match(/[_-]([a-zA-Z0-9]{5,})$/);
    if (suffix && /\d/.test(suffix[1])) return true;
    if (/^[a-z0-9]{6,}$/.test(cls) && /\d/.test(cls)) return true;
    if (
      cls.indexOf('css-') === 0 ||
      cls.indexOf('sc-') === 0 ||
      cls.indexOf('jss') === 0 ||
      cls.indexOf('Mui') === 0
    )
      return true;
    return false;
  }

  function escapeAttr(value) {
    return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  }

  function escapeIdent(value) {
    return String(value)
      .replace(/\\/g, '\\\\')
      .replace(/\./g, '\\.')
      .replace(/#/g, '\\#');
  }

  function normalizeText(text) {
    var normalized = String(text || '')
      .trim()
      .replace(/\s+/g, ' ');
    if (normalized.length > MAX_TEXT_LENGTH) {
      normalized = normalized.substring(0, MAX_TEXT_LENGTH);
    }
    return normalized;
  }

  function positionalSegment(el) {
    var tag = el.tagName.toLowerCase();
    var parent = el.parentElement;
    if (!parent) return tag;
    var index = 1;
    for (var sib = parent.firstElementChild; sib; sib = sib.nextElementSibling) {
      if (sib === el) break;
      if (sib.tagName === el.tagName) index++;
    }
    return tag + ':nth-of-type(' + index + ')';
  }

  function positionalPath(el) {
    var segments = [];
    var node = el;
    var depth = 0;
    while (node && node !== document.body && node !== document.documentElement) {
      if (depth >= MAX_PATH_LEVELS) break;
      segments.unshift(positionalSegment(node));
      node = node.parentElement;
      depth++;
    }
    return segments;
  }

  function rankCandidates(el) {
    var candidates = [];
    var tag = el.tagName.toLowerCase();

    // 1. #id when stable-looking.
    if (el.id && !looksAutoGeneratedId(el.id)) {
      candidates.push('#' + escapeIdent(el.id));
    }

    // 2. Anchor href variants — extremely distinguishing on detail pages
    // (e.g. product link vs seller link share classes but never hrefs).
    if (tag === 'a') {
      var href = el.getAttribute('href');
      if (href) {
        candidates.push('a[href="' + escapeAttr(href) + '"]');
        var pathOnly = href.split('?')[0].split('#')[0];
        if (pathOnly && pathOnly !== href) {
          candidates.push('a[href^="' + escapeAttr(pathOnly) + '"]');
        }
      }
    }

    // 3. data-testid / data-test first, then other data-* attributes.
    var dataKeys = [];
    if (el.getAttribute('data-testid')) dataKeys.push('data-testid');
    if (el.getAttribute('data-test')) dataKeys.push('data-test');
    for (var i = 0; i < el.attributes.length; i++) {
      var name = el.attributes[i].name;
      if (
        name.indexOf('data-') === 0 &&
        name !== 'data-testid' &&
        name !== 'data-test'
      ) {
        dataKeys.push(name);
      }
    }
    for (var j = 0; j < dataKeys.length; j++) {
      var value = el.getAttribute(dataKeys[j]);
      if (value) candidates.push('[' + dataKeys[j] + '="' + escapeAttr(value) + '"]');
    }

    // 4. tag.cls1.cls2 with hashed/utility classes removed.
    var semantic = [];
    if (el.classList) {
      for (var k = 0; k < el.classList.length; k++) {
        if (!isUtilityClass(el.classList[k])) semantic.push(el.classList[k]);
      }
    }
    if (semantic.length) {
      var sel = tag;
      for (var m = 0; m < semantic.length; m++) sel += '.' + escapeIdent(semantic[m]);
      candidates.push(sel);
    }

    // 5. Positional nth-of-type path (limited depth).
    var path = positionalPath(el);
    if (path.length) candidates.push(path.join(' > '));

    return candidates;
  }

  // ---------------- selector validation & xpath ----------------

  // Tests every candidate IN-PAGE at record time: a candidate is kept only
  // when querySelector resolves it, and ranked first when it uniquely
  // identifies the tapped element. Selectors that match a DIFFERENT element
  // (e.g. the seller link when the product link was tapped) are demoted
  // below the verified-unique ones so replay tries the good ones first.
  function validateAndOrder(el, candidates) {
    var unique = [];
    var resolves = [];
    var broken = [];
    for (var i = 0; i < candidates.length; i++) {
      var sel = candidates[i];
      var found = null;
      var count = 0;
      try {
        var all = document.querySelectorAll(sel);
        count = all.length;
        found = count ? all[0] : null;
      } catch (e) {
        broken.push(sel);
        continue;
      }
      if (!found) {
        broken.push(sel);
      } else if (count === 1 && found === el) {
        unique.push(sel);
      } else if (found === el) {
        resolves.push(sel);
      } else {
        broken.push(sel);
      }
    }
    return unique.concat(resolves).concat(broken);
  }

  function xpathSegment(el) {
    var tag = el.tagName.toLowerCase();
    if (el.id && !looksAutoGeneratedId(el.id)) {
      return { tag: tag, id: el.id };
    }
    var index = 1;
    for (
      var sib = el.parentElement ? el.parentElement.firstElementChild : null;
      sib;
      sib = sib.nextElementSibling
    ) {
      if (sib === el) break;
      if (sib.tagName === el.tagName) index++;
    }
    return { tag: tag, index: index };
  }

  // Builds an XPath for the element, anchored at the nearest ancestor with a
  // stable id (falls back to document root). XPath complements CSS when
  // classes/structure shift but position stays stable.
  function buildXPath(el) {
    var parts = [];
    var node = el;
    var anchored = false;
    while (node && node.nodeType === 1) {
      var seg = xpathSegment(node);
      if (seg.id) {
        parts.unshift('//' + seg.tag + '[@id="' + seg.id + '"]');
        anchored = true;
        break;
      }
      parts.unshift('/' + seg.tag + '[' + seg.index + ']');
      node = node.parentElement;
    }
    var xp = parts.join('');
    return anchored ? xp : '/html/body' + xp;
  }

  // ---------------- tap capture ----------------

  var ACTIONABLE = 'a, button, [role="button"], input';

  function resolveActionable(target) {
    if (!target || target.nodeType !== 1) return null;
    var closest = null;
    try {
      closest = target.closest
        ? target.closest(ACTIONABLE)
        : null;
    } catch (e) {}
    return closest || target;
  }

  function onTap(event) {
    try {
      // Ignore synthetic dispatches (element.click() from the dialogue
      // dismisser or the replayer): only real user taps are trusted.
      if (event.isTrusted === false) return;
      var el = resolveActionable(event.target);
      if (!el || !el.tagName) return;
      var text = normalizeText(el.textContent || '');
      var candidates = validateAndOrder(el, rankCandidates(el));
      emit({
        selectorCandidates: candidates,
        xpath: buildXPath(el),
        textContent: text.length ? text : null,
        tagName: el.tagName.toUpperCase(),
        pageUrl: String(window.location.href)
      });
    } catch (e) {}
  }

  document.addEventListener('click', onTap, true);
  document.addEventListener('touchend', onTap, true);
})();
''';
